---
title: "PRISMA_ Maternal-Infant-Constructed-Outcomes"
author: "Fouzia Farooq"
date: "`r Sys.Date()`"
output: pdf_document
---
Constructed variables: 
https://docs.google.com/spreadsheets/d/1dfOWoZNm0RipnIRIucHt3kAFiPl3nISD3U2jA3btKXo/edit#gid=252197818

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
library(readxl)
library(dplyr)
library(ggplot2)
library(knitr)
library(stringr)
library(ThemePark)
library(purrr)
```

```{r}
# path_to_data <- 'Z:/SynapseCSVs/Kenya/2023-07-28/' # If MNH*.xlsx files are located elsewhere, set this to, for example, 'data/' or '//TNT/...'

path_to_data <- 'Z:/Processed Data/2023-07-28/'
```

```{r}

form_data_filename <- paste0(path_to_data, 'MatData_Wide_2023-07-28',".RData")
form_df <- load(form_data_filename)
    
form_data_filename <- paste0(path_to_data, 'InfData_Wide_2023-07-28',".RData")
form_df <- load(form_data_filename)  
    
    
# Create a data subset from maternal and infant files:

inf_subset_df <- InfData_Wide %>% dplyr::select(SITE, MOMID, PREGID, INFANTID, 
                                                M11_INF_DSTERM,
                                                M11_BW_FAORRES, M11_BW_EST_FAORRES,
                                                M11_BREATH_FAIL_CEOCCUR) %>%
  dplyr::filter(!is.na(MOMID)) %>%
  dplyr::filter(!is.na(PREGID)) %>%
  dplyr::filter(!is.na(INFANTID))

mat_subset_df <- MatData_Wide %>% dplyr::select(SITE, MOMID, PREGID, SCRNID, DOB, M01_US_OHOLOC_1, 
                                                M04_FETAL_LOSS_DSSTDAT_1, M04_FETAL_LOSS_DSSTDAT_2,
                                                M04_FETAL_LOSS_DSSTDAT_3,
                                                M04_FETAL_LOSS_DSSTDAT_4, M04_FETAL_LOSS_DSSTDAT_5,
                                                M09_DELIV_DSSTDAT_INF1_6, M09_BIRTH_DSTERM_INF1_6,
                                                M01_GA_LMP_WEEKS_SCORRES_1, M01_GA_LMP_DAYS_SCORRES_1,
                                                M01_US_GA_WKS_AGE_FTS1_1,
                                                M01_US_GA_WKS_AGE_FTS2_1, M01_US_GA_WKS_AGE_FTS2_1,
                                                M01_US_GA_WKS_AGE_FTS3_1, M01_US_GA_WKS_AGE_FTS4_1,
                                                M01_US_GA_DAYS_AGE_FTS1_1, M01_US_GA_DAYS_AGE_FTS2_1,
                                                M01_US_GA_DAYS_AGE_FTS3_1, M01_US_GA_DAYS_AGE_FTS4_1,
                                                M09_CRY_CEOCCUR_INF1_6, M09_FHR_VSTAT_INF1_6, M09_MACER_CEOCCUR_INF1_6,
                                                M09_CORD_PULS_CEOCCUR_INF1_6) %>%
    dplyr::filter(!is.na(MOMID)) %>%
  dplyr::filter(!is.na(PREGID)) %>%
  dplyr::filter(MOMID != "")

temp.df <- mat_subset_df %>% group_by(SITE, MOMID) %>%
  filter(n()>1) %>% ungroup()

temp.df <- inf_subset_df %>% group_by(SITE, MOMID, PREGID) %>%
  filter(n()>1) %>% ungroup() # Shows 25 IDs that are b/c of 12 twins and 1 INFANT ID that is 'n/a' and has the same PREGID as the twins. Will remove this row. Dataset will have n=12 twin pregnancies.

mat_inf_subset_df <- left_join(mat_subset_df, inf_subset_df, by = c("SITE", "MOMID", "PREGID"))

mat_inf_subset_df <- mat_inf_subset_df %>% dplyr::filter(if_else(is.na(INFANTID), TRUE,
                                                                  INFANTID != "n/a")) # Have to be very careful with NA in a logical expression.  Dplyr filter only includes rows where the expression is TRUE but not where it's FALSE or NA.


#3104 after merge might be ok.
# 2543 enrolled and we have 3015 have an MNH02 (Screened but not enrolled.).
# B/c there is no enrollment yes/no variable, Stacie has been doing a variable from: Enrolled when age requirement, viable pregnancy with GA>= weeks by US, Outside catchment area, did not consent.

```

Fetal/Infant outcomes
For GA_BOE: use US_GA_DAYS_AGE_FTS1,2,3,4 and see which one is bigger.  Use the biggest on to do the calculation.  In the constructed outcomes sheets, it is not listed correctly (b/c only asking to use first fetus)
```{r}

```


```{r}

MatData_Wide$M01_US_OHOSTDAT_1 #_1 means first visit (use this for GA calc. )
MatData_Wide$M04_FETAL_LOSS_DSSTDAT_1
sort(colnames(MatData_Wide))
MatData_Wide %>% dplyr::mutate(GA_DIFF_WKS = GA_LMP_WEEKS_SCORRES - US_GA_WKS_AGE_FTS1,
                        GA_DIFF_DAYS = GA_LMP_DAYS_SCORRES - US_GA_DAYS_AGE_FTS1)
```

