---
title:  "<span style='font-size: 18px'> <span style='text-align: center'> PRISMA-Maternal-Outcomes (Maternal Anemia) (Issued: `r Sys.Date()`)"
author: "Author: Fouzia Farooq"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 4
 

---

&nbsp;
&nbsp;
&nbsp;
&nbsp;


##### **Includes data from synapse last updated:** {.unlisted .unnumbered}
#####  2023-10-13 {.unlisted .unnumbered}


```{css, echo=FALSE}
.table caption {
  color: black;
  font-weight: bold;
}
```


```{r, data setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(knitr)
library(tidyverse)
library(reshape2)
library(lubridate)
library(kableExtra)
library(emo)
library(naniar)
library(dplyr)
library(RColorBrewer)
```

```{r}
anemia_df <- read.csv('../data_out/anemia_fortables_20231020.csv')
df <- anemia_df 
```
\newpage

### Maternal Anemia (ANC, L&D, PNC-0, PNC-1, PNC-4)
**Definition:** Hemoglobin (g/dl) below defined cutoff among women who had a delivery date
<br>
<br>

*Denominator: Enrolled women with a delivery date.
<br>
<br>

Table 1: Anemia
```{r}

#TODO: SHOULD I DO THESE OUT OF COMPLETED FORMS? MNH06_COMPLETED
anemia_table <- df %>%
  rowwise() %>%
  group_by(SITE) %>%
  summarise(
    "Missing CBC_HB_LBORRES at Visit 1, n (%)" =
      paste0(sum(is.na(M08_CBC_HB_LBORRES_1) & 
                   ENROLL_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M08_CBC_HB_LBORRES_1) & 
                                ENROLL_PASS==1, na.rm = TRUE)/n()*100, 2),nsmall=2, digits=3),
             ")"),
    
    "Missing HB_POC_LBORRES at Visit 1, n (%)" =
      paste0(sum(is.na(M06_HB_POC_LBORRES_1) & 
                   ENROLL_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M06_HB_POC_LBORRES_1) & 
                                ENROLL_PASS==1, na.rm = TRUE)/n()*100, 2),nsmall=2, digits=3),
             ")"),
    
    "Missing both at Visit 1, n (%)" =
      paste0(sum(is.na(M08_CBC_HB_LBORRES_1) & 
                   is.na(M06_HB_POC_LBORRES_1) & 
                   ENROLL_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M08_CBC_HB_LBORRES_1) & 
                                is.na(M06_HB_POC_LBORRES_1) & 
                                ENROLL_PASS==1, na.rm = TRUE)/n()*100, 2), nsmall=2, digits=3),
             ")"),
    # "anemia category high " = 
    #   paste0(sum(MAT_ANEMIA_MEAS1 == "high hb >=15g/dl")),
    # " (",
    # format(round(sum(MAT_ANEMIA_MEAS1 == "high hb >=15g/dl")/n()*100,2), nsmall=2, digits=3),
    # ")")
    
    # VISIT 2
    "Missing CBC_HB_LBORRES at Visit 2, n (%)" =
      paste0(sum(is.na(M08_CBC_HB_LBORRES_2) &
                   ANC20_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M08_CBC_HB_LBORRES_2) &
                   ANC20_PASS==1, na.rm = TRUE)/n()*100, 2),nsmall=2, digits=3),
             ")"),
    
    "Missing HB_POC_LBORRES at Visit 2, n (%)" =
      paste0(sum(is.na(M06_HB_POC_LBORRES_2) &
                   ANC20_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M06_HB_POC_LBORRES_2)&
                   ANC20_PASS==1, na.rm = TRUE)/n()*100, 2),nsmall=2, digits=3),
             ")"),
    
    "Missing both at Visit 2, n (%)" =
      paste0(sum(is.na(M08_CBC_HB_LBORRES_2) & 
                   is.na(M06_HB_POC_LBORRES_2) &
                   ANC20_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M08_CBC_HB_LBORRES_2) & 
                                is.na(M06_HB_POC_LBORRES_2) &
                   ANC20_PASS==1, na.rm = TRUE)/n()*100, 2), nsmall=2, digits=3),
             ")"),
    
    
    # VISIT 3
    "Missing CBC_HB_LBORRES at Visit 3, n (%)" =
      paste0(sum(is.na(M08_CBC_HB_LBORRES_3) &
                   ANC28_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M08_CBC_HB_LBORRES_3) &
                   ANC28_PASS==1, na.rm = TRUE)/n()*100, 2),nsmall=2, digits=3),
             ")") ,
    
    "Missing HB_POC_LBORRES at Visit 3, n (%)" =
      paste0(sum(is.na(M06_HB_POC_LBORRES_3) &
                   ANC28_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M06_HB_POC_LBORRES_3) &
                   ANC28_PASS==1, na.rm = TRUE)/n()*100, 2),nsmall=2, digits=3),
             ")"),
    
        "Missing both at Visit 3, n (%)" =
      paste0(sum(is.na(M08_CBC_HB_LBORRES_3) & 
                   is.na(M06_HB_POC_LBORRES_3) &
                   ANC28_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M08_CBC_HB_LBORRES_3) & 
                                is.na(M06_HB_POC_LBORRES_3) &
                   ANC28_PASS==1, na.rm = TRUE)/n()*100, 2), nsmall=2, digits=3),
             ")"),
    
    
    # VISIT 4
    "Missing CBC_HB_LBORRES at Visit 4, n (%)" =
      paste0(sum(is.na(M08_CBC_HB_LBORRES_4)),
             " (",
             format(round(sum(is.na(M08_CBC_HB_LBORRES_4) &
                   ANC32_PASS==1, na.rm = TRUE)/n()*100, 2),nsmall=2, digits=3),
             ")"),
    
    "Missing HB_POC_LBORRES at Visit 4, n (%)" =
      paste0(sum(is.na(M06_HB_POC_LBORRES_4) &
                   ANC32_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M06_HB_POC_LBORRES_4) &
                   ANC32_PASS==1, na.rm = TRUE)/n()*100, 2),nsmall=2, digits=3),
             ")"),
    
        "Missing both at Visit 4, n (%)" =
      paste0(sum(is.na(M08_CBC_HB_LBORRES_4) & 
                   is.na(M06_HB_POC_LBORRES_4) &
                   ANC32_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M08_CBC_HB_LBORRES_4) & 
                                is.na(M06_HB_POC_LBORRES_4) &
                   ANC32_PASS==1, na.rm = TRUE)/n()*100, 2), nsmall=2, digits=3),
             ")"),
    
    # VISIT 5
    "Missing CBC_HB_LBORRES at Visit 5, n (%)" =
      paste0(sum(is.na(M08_CBC_HB_LBORRES_5) &
                   ANC36_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M08_CBC_HB_LBORRES_5) &
                   ANC36_PASS==1, na.rm = TRUE)/n()*100, 2),nsmall=2, digits=3),
             ")") ,
    
    "Missing HB_POC_LBORRES at Visit 5, n (%)" =
      paste0(sum(is.na(M06_HB_POC_LBORRES_5) &
                   ANC36_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M06_HB_POC_LBORRES_5))/n()*100, 2),nsmall=2, digits=3),
             ")"),
    
        "Missing both at Visit 5, n (%)" =
      paste0(sum(is.na(M08_CBC_HB_LBORRES_5) & 
                   is.na(M06_HB_POC_LBORRES_5) &
                   ANC36_PASS==1, na.rm = TRUE),
             " (",
             format(round(sum(is.na(M08_CBC_HB_LBORRES_5) & 
                                is.na(M06_HB_POC_LBORRES_5) &
                   ANC36_PASS==1, na.rm = TRUE)/n()*100, 2), nsmall=2, digits=3),
             ")"),
    
    # IPC - VISIT 6 - THESE ARE AMONG THOSE WHO HAVE DELIVERED, WHICH IS ALREADY MY SUBSET. SO DON'T NEED TO DO ANY WINDOW PASS
    "Missing (or optional) CBC_HB_LBORRES at delivery, n (%)" =
      paste0(sum(is.na(M08_CBC_HB_LBORRES_6)),
             " (",
             format(round(sum(is.na(M08_CBC_HB_LBORRES_6))/n()*100, 2),nsmall=2, digits=3),
             ")"),
        
    "Missing (or optional_ HB_POC_LBORRES at delivery, n (%)" =
      paste0(sum(is.na(M06_HB_POC_LBORRES_6)),
             " (",
             format(round(sum(is.na(M06_HB_POC_LBORRES_6))/n()*100, 2),nsmall=2, digits=3),
             ")"),
    
        "Missing (or optional) both at delivery, n (%)" =
      paste0(sum(is.na(M08_CBC_HB_LBORRES_6) & is.na(M06_HB_POC_LBORRES_6)),
             " (",
             format(round(sum(is.na(M08_CBC_HB_LBORRES_6) & is.na(M06_HB_POC_LBORRES_6))/n()*100, 2), nsmall=2, digits=3),
             ")"))%>%
  
  t() %>% as.data.frame() %>% 
  `colnames<-`(c(.[1,])) %>% 
  slice(-1)
    
```
 
```{r}
anemia_table  %>% 
  `rownames<-` (c(
    "Missing CBC_HB_LBORRES at Enrollment, n (%)",
    "Missing HB_POC_LBORRES at Enrollment, n (%)",
    "Missing both at Enrollment, n(%)",
    
    "Missing CBC_HB_LBORRES at ANC20, n (%)",
    "Missing HB_POC_LBORRES at ANC20, n (%)",
    "Missing both at ANC20, n(%)",
    
    "Missing CBC_HB_LBORRES at ANC28, n (%)",
    "Missing HB_POC_LBORRES at ANC28, n (%)",
    "Missing both at ANC28, n(%)",
    
    "Missing CBC_HB_LBORRES at ANC32, n (%)",
    "Missing HB_POC_LBORRES at ANC32, n (%)",
    "Missing both at ANC32, n(%)",
    
    "Missing CBC_HB_LBORRES at ANC36, n (%)",
    "Missing HB_POC_LBORRES at ANC36, n (%)",
    "Missing both at ANC36, n(%)",
    
    "Missing (or optional) CBC_HB_LBORRES at delivery, n (%)",
    "Missing (or optional) HB_POC_LBORRES at delivery, n (%)",
    "Missing (or optional) both at delivery, n(%)")) %>%
  
  
  mutate_all(funs(str_replace(., "NaN", "0"))) %>% 
  kbl(caption = "", booktabs = TRUE) %>%
  kable_paper(bootstrap_options = "striped", 
              full_width = T, html_font = "Cambria", position = "left",
              latex_options = c("repeat_header", "HOLD_position")) %>% 
  kable_styling(font_size = 14) %>%
  row_spec(0, extra_css = "border-bottom: 0px white;") #

 #"Missing M08_CBC_HB_LBORRES_1 = NA, n (%)",#%>% 
 # pack_rows("PRISMA measured birthweight (categorical), n (%)", 5, 8, label_row_css = "color: steelblue;") %>% 
  # pack_rows("Any method measured birthweight (categorical), n (%)", 9, 12, label_row_css = "color: steelblue;") 
```




